# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_PHY_ZHIHE_A210_E16) += phy-zhihe-a210-e16.o
obj-$(CONFIG_PHY_ZHIHE_A210_USB2) += phy-zhihe-a210-usb2.o
obj-$(CONFIG_PHY_ZHIHE_A210_C10) += phy-zhihe-a210-c10.o
