# SPDX-License-Identifier: GPL-2.0

spacemit-drm-y := spacemit_drm.o \
		  spacemit_crtc.o \
		  spacemit_cmdlist.o \
		  spacemit_planes.o \
		  spacemit_dmmu.o \
		  dpu/dpu_saturn.o \
		  dpu/dpu_saturn_hee.o \
		  dpu/saturn_fbcmem.o

spacemit-inno-dp-y := spacemit_inno_dp.o

obj-$(CONFIG_DRM_SPACEMIT) += spacemit-drm.o
obj-$(CONFIG_SPACEMIT_INNO_DP) += spacemit-inno-dp.o
